spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/db_dev;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update # 개발 환경에서는 자동으로 DDL을 업데이트